# Generated by Django 4.0.5 on 2022-07-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Porfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciasmodels',
            name='imagen',
        ),
    ]
